import { SEO } from '../components/seo/SEO';

export function TermsOfService() {
    return (
        <>
            <SEO title="Terms of Service" description="Terms of service and liability coverages for HelloFlint's AI applications." url="https://helloflint.agency/terms" />
            <div className="pt-32 pb-24 min-h-screen bg-background">
                <div className="max-w-3xl mx-auto px-4 sm:px-6">

                    <header className="mb-12">
                        <h1 className="text-4xl md:text-5xl font-heading text-primary leading-tight tracking-tight mb-6">
                            Terms of Service
                        </h1>
                        <p className="text-xl text-primary/60">
                            Last updated: {new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}
                        </p>
                    </header>

                    <div className="prose prose-lg prose-headings:font-heading prose-headings:text-primary prose-p:text-primary/80 prose-a:text-accent-action max-w-none">
                        <h2>1. Agreement to Terms</h2>
                        <p>
                            These Terms of Service constitute a legally binding agreement between you, whether personally or on behalf of an entity ("you") and HelloFlint ("we", "us", or "our"), concerning your access to and use of the helloflint.co.uk website and our AI development services.
                        </p>

                        <h2>2. Intellectual Property & Ownership</h2>
                        <p>
                            Upon completion of your project and full payment, you own the configuration and prompts created for your AI assistant. You retain full control over your API keys, hosting environments, and customer data. We do not claim ownership over the assistants we build and hand over to you.
                        </p>

                        <h2>3. Liability</h2>
                        <p>
                            While we design our AI systems with guardrails, strict prompting, and high-quality models (e.g., Anthropic Claude), artificial intelligence can be unpredictable (sometimes known as "hallucinations"). HelloFlint cannot be held liable for specific outputs generated by your AI assistant once deployed, nor for any business loss, revenue loss, or data loss resulting from automated interactions.
                        </p>
                        <p>
                            You agree that it is your responsibility to monitor and periodically review the outputs of your assistant.
                        </p>

                        <h2>4. Ongoing Costs</h2>
                        <p>
                            Unless explicitly covered by an ongoing Support Retainer, HelloFlint is not responsible for the ongoing running costs of the APIs, hosting platforms, or third-party messaging services required to keep your assistant live. These services are billed directly to you by the respective providers.
                        </p>

                        <h2>5. Refunds & Refinements</h2>
                        <p>
                            We operate on a predefined refinement period (e.g., 14, 30, or 60 days depending on your package). We will make necessary adjustments to the prompt logic during this phase. If you require further structural changes after the refinement period, they may be subject to additional consulting fees.
                        </p>

                        <h2>6. Governing Law</h2>
                        <p>
                            These conditions are governed by and interpreted following the laws of the United Kingdom. If you have a dispute, we will attempt to resolve it informally first.
                        </p>
                    </div>
                </div>
            </div>
        </>
    );
}
